# Generated by Django 4.0.4 on 2022-09-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='created_at',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
