# Generated by Django 4.0.4 on 2022-09-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_alter_user_details_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namesd', models.TextField(max_length=1600)),
            ],
        ),
    ]
