# Generated by Django 4.0.4 on 2022-09-02 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_dbo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbo',
            name='id',
        ),
        migrations.AddField(
            model_name='dbo',
            name='user_details_ptr',
            field=models.OneToOneField(auto_created=True, default=2, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='signup.user_details'),
            preserve_default=False,
        ),
    ]
