# Generated by Django 4.0.4 on 2022-09-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_remove_dbo_id_dbo_user_details_ptr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
