# Generated by Django 4.0.4 on 2022-09-16 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_alter_user_details_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='updated_at',
            field=models.DateTimeField(),
        ),
    ]
